# Generated by Django 6.0.1 on 2026-01-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('AIML', 'AI/ML'), ('TOOLS', 'Tools/Others')], default='TOOLS', max_length=20),
        ),
    ]
